services:
  cryptocurrency:
    build: .
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - .:/cryptocurrency
      - /cryptocurrency/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true